# Generated by Django 4.2.9 on 2024-01-29 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ToDoAPP", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo_table",
            name="task_date_time",
            field=models.TimeField(auto_now=b"I01\n"),
        ),
    ]
