# Generated by Django 4.2.9 on 2024-01-29 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ToDoAPP", "0002_alter_todo_table_task_date_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo_table",
            name="task_date_timeold",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
