# Generated by Django 4.2.9 on 2024-01-29 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ToDoAPP", "0003_todo_table_task_date_timeold"),
    ]

    operations = [
        migrations.RemoveField(model_name="todo_table", name="task_date_timeold",),
    ]
